baseURL = 'https://github.com/gabrielhuang00/my_website'  # replace later with real GitHub Pages URL
languageCode = 'en-us'
title = 'Gabriel Huang'
theme = 'PaperMod'
publishDir = "docs"

[params]
  ShowReadingTime = true
  ShowToc = true